security:
    encoders:
            AppBundle\Data\MUS\Usuario:
                algorithm: sha1
                iterations: 1
                encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AppBundle\Data\MUS\Usuario , property: username }

    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /

            logout:
                path:  /logout
                target: /
            security: true
            anonymous: true
        #login_firewall:
         #   pattern: ^/login$
         #   anonymous:

    access_control:
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, roles: ROLE_ADMIN}
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: /admin/, roles: ROLE_ADMIN, requires_channel: http }
        #- { path: /admin$, roles: ROLE_ADMIN, requires_channel: http }
